[darwin] more bin script fixes

diff --git a/darwin/build-pprz-binary b/darwin/build-pprz-binary
--- a/darwin/build-pprz-binary
+++ b/darwin/build-pprz-binary
@@ -116,7 +116,7 @@ echo "********************CHECKING FOR SUPPORTED OS"
 platform='unknown'
 unamestr=`uname`
 if [[ "$unamestr" != 'Darwin' ]]; then
-   echo "Platform $unamestr is NOT SUPPORTED - OS X Only!"
+   echo "build-pprz-binary: Platform $unamestr is NOT SUPPORTED - OS X Only!"
    exit 1
 fi
 
@@ -131,11 +131,11 @@ case "$OSX_VERSION_NUM" in
 esac
 
 if [[ $OSX_VERSION == 'NotSupported' ]]; then
-	echo "OS X Version is NOT SUPPORTED - Version $OSX_VERSION_NUM"
+	echo "build-pprz-binary: OS X Version is NOT SUPPORTED - Version $OSX_VERSION_NUM"
 	exit 1
 fi
 
-echo "Running on OS X $OSX_VERSION"
+echo "build-pprz-binary: Running on OS X $OSX_VERSION"
 
 # Verify Macports is installed correctly - check the install dir - print instructions if required
 # TODO
@@ -149,12 +149,12 @@ fi
 echo "********************UPDATING MACPORTS SOURCES"
 $PORTCMD selfupdate
 if [[ $? != 0 ]]; then
-	echo "Error running PORT selfupdate!"
+	echo "build-pprz-binary: Error running PORT selfupdate!"
 	exit 1
 fi
 $PORTCMD selfupdate
 if [[ $? != 0 ]]; then
-	echo "Error running PORT selfupdate!"
+	echo "build-pprz-binary: Error running PORT selfupdate!"
 	exit 1
 fi
 
@@ -163,17 +163,17 @@ echo "********************UNINSTALLING AND CLEANING ALL INSTALLED PORTS"
 #Install expat so that the "port -f uninstall installed" will always have something to uninstall and expat is small
 $PORTCMD install expat
 if [[ $? != 0 ]]; then
-	echo "Error running PORT install expat!"
+	echo "build-pprz-binary: Error running PORT install expat!"
 	exit 1
 fi
 $PORTCMD -f uninstall installed
 if [[ $? != 0 ]]; then
-	echo "Error running PORT uninstall!"
+	echo "build-pprz-binary: Error running PORT uninstall!"
 	exit 1
 fi
 $PORTCMD clean --all uninstalled
 if [[ $? != 0 ]]; then
-	echo "Error running PORT clean!"
+	echo "build-pprz-binary: Error running PORT clean!"
 	exit 1
 fi
 
@@ -181,19 +181,19 @@ fi
 echo "********************INSTALLING GIT FROM MACPORTS"
 $PORTCMD install git-core
 if [[ $? != 0 ]]; then
-	echo "Error running PORT install git-core!"
+	echo "build-pprz-binary: Error running PORT install git-core!"
 	exit 1
 fi
 
 # Clone the source from GitHub after deleting any existing
 echo "********************CLONING FRESH paparazzi-portability-support FROM GITHUB"
 if [ -d "paparazzi-portability-support" ]; then
-	echo "Removing existing paparazzi-portability-support directory"
+	echo "build-pprz-binary: Removing existing paparazzi-portability-support directory"
 	rm -rf ./paparazzi-portability-support
 fi
 $GITCMD clone https://github.com/scdwyer/paparazzi-portability-support.git --branch $GITBRANCH
 if [[ $? != 0 ]]; then
-	echo "Error cloning source directory!"
+	echo "build-pprz-binary: Error cloning source directory!"
 	exit 1
 fi
 
@@ -203,7 +203,7 @@ echo "********************ADDING paparazzi-portability-support DIRECTORY TO MACP
 
 POST_LINE_NUM=`sed -n '/^rsync:/=' $PORT_SOURCES_CONF_PATH.default | sed q`
 if [[ $? != 0 ]]; then
-	echo "Error running sed on sources.conf!"
+	echo "build-pprz-binary: Error running sed on sources.conf!"
 	exit 1
 fi
 ADD_LINE="file://$DATA_DIR/paparazzi-portability-support/darwin/macports/ports"
@@ -212,7 +212,7 @@ sed ''"$POST_LINE_NUM"' i\
        '"$ADD_LINE"'
        ' $PORT_SOURCES_CONF_PATH.default > $PORT_SOURCES_CONF_PATH
 if [[ $? != 0 ]]; then
-	echo "Error running sed to update sources.conf!"
+	echo "build-pprz-binary: Error running sed to update sources.conf!"
 	exit 1
 fi
 
@@ -220,7 +220,7 @@ fi
 echo "********************CURRENT MACPORTS SOURCES"
 sed -n '/^[fr]/p' $PORT_SOURCES_CONF_PATH
 if [[ $? != 0 ]]; then
-	echo "Error printing sources.conf entries with sed!"
+	echo "build-pprz-binary: Error printing sources.conf entries with sed!"
 	exit 1
 fi
 
@@ -228,7 +228,7 @@ fi
 echo "********************UPDATING MACPORTS SOURCES"
 $PORTCMD selfupdate
 if [[ $? != 0 ]]; then
-	echo "Error running PORT selfupdate for the second time!"
+	echo "build-pprz-binary: Error running PORT selfupdate for the second time!"
 	exit 1
 fi
 
@@ -237,24 +237,37 @@ echo "********************BUILDING THE paparazzi-tools PACKAGE"
 export PATH=$PATH:/opt/paparazzi/bin
 $PORTCMD -k mpkg paparazzi-tools
 if [[ $? != 0 ]]; then
-	echo "Error building the mpkg! Trying to recover..."
+	echo "build-pprz-binary: Error building the mpkg! Trying to recover..."
 	# Find what port failed to install
-	$FAILEDPORT=`cat $LOG | sed -n 's/Error: Failed to install \(.*\)/\1/p'`
-	echo "The port $FAILEDPORT failed to install..."
-	$REMAININGDEPS=`cat $LOG | sed -n 's/Error: The following dependencies were not installed: \(.*\)/\1/p'`
-	$DEPSTOINSTALL=`echo $REMAININGDEPS | sed -n 's/$FAILEDPORT//p'`
-	echo "Will attempt to install the other dependencies manually after cleaning $FAILEDPORT"
-	echo "The remaining dependencies minus the failed one are: $DEPSTOINSTALL"
+	FAILEDPORT=`cat $LOG | sed -n 's/Error: Failed to install \(.*\)/\1/p' | tail -1`
+	echo "build-pprz-binary: The port $FAILEDPORT was the last port that failed to install..."
+	REMAININGDEPS=`cat $LOG | sed -n 's/Error: The following dependencies were not installed: \(.*\)/\1/p' | tail -1`
+	DEPSTOINSTALL=`echo $REMAININGDEPS | sed -n "s/$FAILEDPORT//p"`
+	echo "build-pprz-binary: Will attempt to install the other dependencies manually after cleaning $FAILEDPORT"
+	echo "build-pprz-binary: The remaining dependencies minus the failed one are: $DEPSTOINSTALL"
 	$PORTCMD clean $FAILEDPORT
 	$PORTCMD install $DEPSTOINSTALL
 	if [[ $? != 0 ]]; then
-		echo "Error trying to recover from the failed mpkg build...Exiting."
-		exit 1
+		echo "build-pprz-binary: Error trying to recover from the failed mpkg build...trying again with reduced dependencies."
+		# Find what port failed to install
+		FAILEDPORT=`cat $LOG | sed -n 's/Error: Failed to install \(.*\)/\1/p' | tail -1`
+		echo "build-pprz-binary: The port $FAILEDPORT was the last port that failed to install..."
+		REMAININGDEPS=`cat $LOG | sed -n 's/Error: The following dependencies were not installed: \(.*\)/\1/p' | tail -1`
+		DEPSTOINSTALL=`echo $REMAININGDEPS | sed -n "s/^[-_a-zA-Z0-9]* $FAILEDPORT [-_a-zA-Z0-9]*//p"`
+		echo "build-pprz-binary: Will attempt to install the other dependencies manually after cleaning $FAILEDPORT"
+		echo "build-pprz-binary: The remaining dependencies minus the failed one and the two surrounding are: $DEPSTOINSTALL"
+		$PORTCMD clean $FAILEDPORT
+		$PORTCMD install $DEPSTOINSTALL
+		if [[ $? != 0 ]]; then
+			echo "build-pprz-binary: Error trying to recover from the failed mpkg build a second time. Exiting."
+			exit 1
+		fi
 	fi
+
 	# Try the mpkg again
 	$PORTCMD -k mpkg paparazzi-tools
 	if [[ $? != 0 ]]; then
-		echo "Error trying to build the mpkg the second time...Exiting."
+		echo "build-pprz-binary: Error trying to build the mpkg the second time...Exiting."
 		exit 1
 	fi
 fi
@@ -271,7 +284,7 @@ else
 fi
 cp -r `find /opt/paparazzi/var/macports/build/* -name paparazzi-tools-*.mpkg` $DMG_DIR
 if [[ $? != 0 ]]; then
-	echo "Error copying the mpkg!"
+	echo "build-pprz-binary: Error copying the mpkg!"
 	exit 1
 fi
 
@@ -279,7 +292,7 @@ fi
 echo "********************COPYING THE paparazzi-tools RESOURCES TO THE DMG_DIR"
 cp -r ./paparazzi-portability-support/darwin/install/Contents/* $DMG_DIR/paparazzi-tools*.mpkg/Contents/
 if [[ $? != 0 ]]; then
-	echo "Error copying the resources!"
+	echo "build-pprz-binary: Error copying the resources!"
 	exit 1
 fi
 
@@ -287,7 +300,7 @@ fi
 echo "********************CHANGING THE POSTFLIGHT SCRIPT PERMISSIONS"
 chmod 777 $DMG_DIR/paparazzi-tools*.mpkg/Contents/Resources/postflight
 if [[ $? != 0 ]]; then
-	echo "Error changing postflight file permissions!"
+	echo "build-pprz-binary: Error changing postflight file permissions!"
 	exit 1
 fi
 
@@ -295,7 +308,7 @@ fi
 echo "********************CHANGING THE POSTFLIGHT SCRIPT OWNER"
 chown root:admin $DMG_DIR/paparazzi-tools*.mpkg/Contents/Resources/postflight
 if [[ $? != 0 ]]; then
-	echo "Error changing postflight file ownership!"
+	echo "build-pprz-binary: Error changing postflight file ownership!"
 	exit 1
 fi
 
@@ -307,7 +320,7 @@ echo $CURR_DATETIME >> $DATA_DIR/pprzbininstaller_build_date_list.txt
 # Build to .dmg file
 $DATA_DIR/paparazzi-portability-support/darwin/create-dmg --window-size 500 200 --background paparazzi-portability-support/darwin/background.png --icon-size 96 --volname Paparazzi\ Tools --icon `ls -1 $DMG_DIR` 300 70 paparazzi-tools-"$OSX_VERSION"_"$CURR_DATETIME".dmg $DATA_DIR
 if [[ $? != 0 ]]; then
-	echo "Error building DMG file!"
+	echo "build-pprz-binary: Error building DMG file!"
 	exit 1
 fi
 
